name: Cache
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: test-${{ runner.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/cache
          restore-keys: |
            test-${{ runner.os }}-
      - run: |
          if [[ -f "${{ github.workspace }}/cache" ]]; then exit 0; fi
          dd if=/dev/urandom of=${{ github.workspace }}/cache bs=1M count=10
      - run: |
          ls -l ${{ github.workspace }}/cache
