name: Manual matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node: 18
          - os: windows-latest
            node: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: echo "This is running on ${{ matrix.os }} with Node.js ${{ matrix.node }}"
        shell: bash
