name: Manual
on:
  workflow_dispatch: # 手動トリガー
    inputs: # 入力パラメータの定義
      greeting: # パラメータ名
        type: string # パラメータの型
        default: "Hello" # デフォルト値
        required: true # 必須パラメータ
        description: "Enter a greeting message" # パラメータの説明
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Display Greeting
        run: echo "${{ inputs.greeting }}" # 入力された挨拶メッセージを出力
