name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }} # GitHubのシークレットからPASSWORDを環境変数に設定
    steps:
      - name: Print Secret with Masking
        run: | # 定義した環境変数の値を出力
          echo "The value of PASSWORD is: '${PASSWORD}'"
      - name: Print Secret with No Masking
        run: | # 定義した環境変数の値を出力（マスキングなし）
          echo "The value of PASSWORD is: ${PASSWORD:0:1} ${PASSWORD#?}"
